:wrench: Fixed missing library in Dockerfile
#9 736.1 /opt/OCCT/src/Font/Font_FontMgr.cxx:83:14: fatal error: fontconfig/fontconfig.h: No such file or directory
#9 736.1    83 |     #include <fontconfig/fontconfig.h>
#9 736.1       |              ^~~~~~~~~~~~~~~~~~~~~~~~~
#9 736.1 compilation terminated.